language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: bionic
osx_image: xcode12

cache:
  ccache: true

env:
  - METHOD=FetchContent
  - METHOD=ExternalProject
  - METHOD=LocalInstall

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh
